config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events do
    resources :movies, only: [:create, :destroy] do
      get 'vote', on: :member
    end
  end

  authenticated :user do
   root to: "events#index", as: "user_root"
  end

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :movies, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :occurs_at, presence: true

  validates :location, presence: true,
                       uniqueness: {
                         scope: :occurs_at,
                         case_sensitive: false,
                         message: 'event already scheduled for that time'
                       }

  def winning_movie
    Vote.where(movie: movies).select(:movie_id).group(:movie_id).order('count(id) desc').first.movie
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :event
  has_many :votes, dependent: :destroy

  validates :event, presence: true
  validates :url, presence: true

  validates :title, presence: true,
                    uniqueness: {
                      scope: :event_id,
                      case_sensitive: false,
                      message: 'already suggested for that event'
                    }

  def vote(user)
    Vote.create(movie: self, event: event, user: user)
  end

  after_create :update_poster_path

  def update_poster_path
    found_movies = Tmdb::Movie.find(self.title)
    if found_movies.any?
      self.poster_url = found_movies.first.poster_path
      save
    end
  end

  def get_poster_url(width=500)
    config = Tmdb::Configuration.new
    "#{config.base_url}w#{width}#{self.poster_url}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :event
  belongs_to :movie
  belongs_to :user

  validates :event, presence: true
  validates :movie, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @query = params[:search]

    if @query.present?
      @events = Event.where('location ILIKE ?', "%#{@query}%")

      # Also search by movie title
      movies = Movie.where('title ILIKE ?', "%#{@query}%")
      @events += movies.map(&:event)
      @events.uniq!
    else
      @events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @movie = Movie.new
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event created successfully'
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: 'Event created successfully'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])

    @event.destroy
    redirect_to events_url, notice: 'Event deleted successfully'
  end

  private

    def event_params
      params.require(:event).permit(:location, :occurs_at, :search)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @movie = @event.movies.build(movie_params)

    if @movie.save
      redirect_to @event, notice: 'Movie created successfully'
    else
      render 'events/show'
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @movie = Movie.find(params[:id])

    @movie.destroy
    redirect_to @event, notice: 'Movie deleted successfully'
  end

  def vote
    @event = Event.find(params[:event_id])
    @movie = Movie.find(params[:id])

    @vote = @movie.vote(current_user)

    respond_to do |format|
      format.html { redirect_to @event, notice: "Voted for #{@movie.title}" }
      format.js
    end
  end

  private

    def movie_params
      params.require(:movie).permit(:event_id, :title, :url)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@event) do |f| %>
      <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :occurs_at, 'Date/Time' %>
        <%= f.text_field :occurs_at, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/_vote_history.html.erb
<% if @event.votes.count > 0 %>
  <hr>

  <h3>Vote History</h3>

  <div class="row">
    <div class="col-md-6">
      <table class="table vote-list">
        <thead>
          <tr>
            <th>User</th>
            <th>Movie</th>
            <th>Vote Date</th>
          </tr>
        </thead>
        <tbody>
          <% @event.votes.sort { |a, b| b.created_at <=> a.created_at }.each do |vote| %>
            <%= render partial: 'events/vote_history_row', locals: { vote: vote } %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/events/_vote_history_row.html.erb
<tr>
  <td><%= vote.user.name %></td>
  <td><%= vote.movie.title %></td>
  <td><%= vote.created_at %></td>
</tr>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<% content_for :page_title do %>
  Edit Event
<% end %>

<%= render 'form' %>

app/views/events/index.html.erb
<% content_for :page_title do %>
  Events
<% end %>

<% if @events.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Location</th>
        <th>Date/Time</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <th><%= link_to event.location, event %></th>
          <th><%= event.occurs_at %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sorry, no events found.</p>
<% end %>

<a href="<%= new_event_path %>" class="btn btn-primary">Create Event</a>

app/views/events/new.html.erb
<% content_for :page_title do %>
  New Event
<% end %>

<%= render 'form' %>

app/views/events/show.html.erb
<% content_for :page_title do %>
  <%= @event.location %>

  <small>
   <%= @event.occurs_at %> (<%= distance_of_time_in_words_to_now(@event.occurs_at) %>)
  </small>

  <div class="pull-right title-nav">
    <%= link_to "Edit", edit_event_path(@event) %>
    | <%= link_to "Delete", @event, method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %>
  </div>
<% end %>

<% content_for :nav do %>
  <%= link_to "Back to All Events", events_path %>
<% end %>

<% if @event.movies.any? %>
  <table class="table table-striped movie-list">
    <thead>
      <tr>
        <th colspan="2">Title</th>
        <th>Votes</th>
        <th colspan="2"></td>
      </tr>
    </thead>
    <% @event.movies.select { |m| m.persisted? }.each do |movie| %>
      <tr data-movie-id="<%= movie.id %>">
        <td><%= link_to movie.title, movie.url %></td>
        <td><%= image_tag movie.get_poster_url(154) %></td>
        <td class="vote-count"><%= movie.votes.count %></td>
        <td><%= link_to "Vote", vote_event_movie_path(@event, movie), remote: true %></td>
        <td><%= link_to "Delete", event_movie_path(@event, movie), method: :delete, data: { confirm: "Are you sure you want to delete #{movie.title}?" } %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<div class="vote-history">
  <%= render 'events/vote_history' %>
</div>


<div class="row">
  <div class="col-md-6">
    <h3>Add a Movie</h3>
    <% if @movie.errors.any? %>
      <ul class="error-list text-danger">
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for(@movie, url: event_movies_path(@event)) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: "form-control" %>
      </div>

      <%= f.submit "Suggest Movie", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Movie Night</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <%= image_tag "logos/logo.svg" %>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Events", events_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <%= form_tag events_path, method: :get do %>
        <%= label_tag :search %>
        <%= text_field_tag :search, @query %>
        <%= submit_tag 'Search Events' %>
      <% end %>

      <% if content_for? :page_title %>
        <div class="page-header">
          <% if content_for? :nav %>
            <%= yield :nav %>
          <% end %>

          <h1><%= yield :page_title %></h1>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/vote.js.erb
$('.movie-list tr[data-movie-id="<%= @movie.id %>"] .vote-count').html("<%= @movie.votes.count %>");

$('.vote-history tbody').prepend("<%= escape_javascript( render partial: 'events/vote_history_row', locals: { vote: @vote } ) %>");